"""Initial migration

Revision ID: 2991850e877a
Revises: e51cb5c0501f
Create Date: 2025-02-27 14:47:33.366149

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2991850e877a'
down_revision = 'e51cb5c0501f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.alter_column('filedata',
               existing_type=mysql.MEDIUMBLOB(),
               type_=sa.LargeBinary(length=2097152),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.alter_column('filedata',
               existing_type=sa.LargeBinary(length=2097152),
               type_=mysql.MEDIUMBLOB(),
               existing_nullable=True)

    # ### end Alembic commands ###
